// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtcaXSrgr_o2_laoedKLSM9WBdQALqI_8',
    appId: '1:63563171674:web:70710b9336c2bef51ad563',
    messagingSenderId: '63563171674',
    projectId: 'chatapp-f513c',
    authDomain: 'chatapp-f513c.firebaseapp.com',
    storageBucket: 'chatapp-f513c.firebasestorage.app',
    measurementId: 'G-HMH3SZX50C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMvMkt8SbJAzKr8WuWMyRbSjY5nPLSl0',
    appId: '1:63563171674:android:c373b8efc4e8b3dc1ad563',
    messagingSenderId: '63563171674',
    projectId: 'chatapp-f513c',
    storageBucket: 'chatapp-f513c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4DiBmS5efxqunoeWvpNVxy6UT8cU2Xs',
    appId: '1:63563171674:ios:f15e27788b2a76871ad563',
    messagingSenderId: '63563171674',
    projectId: 'chatapp-f513c',
    storageBucket: 'chatapp-f513c.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4DiBmS5efxqunoeWvpNVxy6UT8cU2Xs',
    appId: '1:63563171674:ios:f15e27788b2a76871ad563',
    messagingSenderId: '63563171674',
    projectId: 'chatapp-f513c',
    storageBucket: 'chatapp-f513c.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtcaXSrgr_o2_laoedKLSM9WBdQALqI_8',
    appId: '1:63563171674:web:6dbdceeeb40b9ea31ad563',
    messagingSenderId: '63563171674',
    projectId: 'chatapp-f513c',
    authDomain: 'chatapp-f513c.firebaseapp.com',
    storageBucket: 'chatapp-f513c.firebasestorage.app',
    measurementId: 'G-PTMZLHN581',
  );
}
